[tools]
hadolint="latest"

[tasks.build]
run="""
  podman build {{ config_root}} \
  -t claude-code:latest
"""

[tasks.'build:rust']
depends = ["build"]
run="""
  podman build {{ config_root}} \
  -f Containerfile.rust \
  -t claude-code:rust
"""

[tasks.'build:rust-wasm']
depends = ["build:rust"]
run="""
  podman build {{ config_root}} \
  -f Containerfile.rust-wasm \
  -t claude-code:rust-wasm
"""
