name: Build and Publish OCI Container with Podman

on:
  push:
    branches: ['main', 'master', 'test']

jobs:
  build-and-push:
    runs-on: debian-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          apt-get update
          apt-get -y install podman

      - name: Configure rootless containers
        run: |
          mkdir -p $HOME/.config/containers
          cat > $HOME/.config/containers/storage.conf << EOF
          [storage]
          driver = "vfs"
          runroot = "$HOME/.local/share/containers/storage"
          graphroot = "$HOME/.local/share/containers/storage"
          EOF
          
          cat > $HOME/.config/containers/containers.conf << EOF
          [engine]
          cgroup_manager = "cgroupfs"
          events_logger = "file"
          runtime = "runc"
          EOF

      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          extra-args: |
            --storage-driver=vfs
            --storage-opt=vfs.imagestore=$HOME/.local/share/containers/storage

      - name: Log in to Gitea Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ github.server_url }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ github.server_url }}

